# Autogenerated wrapper script for AsmJit_jll for i686-linux-gnu
export libasmjit

JLLWrappers.@generate_wrapper_header("AsmJit")
JLLWrappers.@declare_library_product(libasmjit, "libasmjit.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libasmjit,
        "lib/libasmjit.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
