# Autogenerated wrapper script for AsmJit_jll for x86_64-apple-darwin
export libasmjit

JLLWrappers.@generate_wrapper_header("AsmJit")
JLLWrappers.@declare_library_product(libasmjit, "@rpath/libasmjit.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libasmjit,
        "lib/libasmjit.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
