# Autogenerated wrapper script for AsmJit_jll for x86_64-w64-mingw32
export libasmjit

JLLWrappers.@generate_wrapper_header("AsmJit")
JLLWrappers.@declare_library_product(libasmjit, "libasmjit.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libasmjit,
        "bin\\libasmjit.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
